name: rnafusion-arriba-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - arriba=1.1.0
  - bioconda::star=2.7.0f
  - bioconda::samtools=1.9
  - conda-forge::r-circlize
  - conda-forge::readline=6.2
  - bioconda::bioconductor-genomicalignments
  - bioconda::bioconductor-genomicranges