name: rnafusion-star-fusion-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::star=2.7.0f
  - bioconda::star-fusion=1.6.0
  - bioconda::trinity=2.6.6
  - conda-forge::perl-carp-assert
  - bioconda::hmmer=3.2.1
  - conda-forge::unzip=6.0
  - bioconda::dfam=2.0
